### PR TITLE
add Ed25519 (15) and Ed448 (16) algorithms

### PR DESCRIPTION
**Pull request by Stricted**

### CODE REVIEW

**Comment by pawal** [comment]
Please merge this @matsduf - also see #117

**Comment by einar** [comment]
The makefile requires net::dns::sec 0.17 (or higher) but this would probably need bleeding edge net::dns::sec that very well may have broken backwards compat (if support even exists, these algos are insanely new). For this reason I wouldnt merge this before actual support, and non-breakage, has been confirmed properly.

**Comment by matsduf** [comment]
@Stricted, there is one more place that should be updated to keep code in sync. It is not strictly necessary, but it is confusing otherwise. Can you update the PR?

line 73-75 (75-77) in engine/lib/DNSCheck/Test/DNSSEC.pm

```
     elsif ( $aid >= 13 and $aid <= 122 ) {
         return "Unassigned ($aid)";
     }

```
It should probably be `$aid >= 17`.

**Comment by Stricted** [comment]
@matsduf good catch, fixed

**Pull request merged**
